name: Ruby

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.2.2"
      - name: Read gem version
        id: gem_version
        run: |
          version=$(ruby -r rubygems -e "spec = Gem::Specification::load(Dir.glob('*.gemspec').first); puts spec.version")
          echo "gem_version=$version" >> $GITHUB_ENV
        shell: bash
      - name: Create Release
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const { repo: { owner, repo } } = context;
            const tag_name = "v" + process.env.gem_version;
            const release = await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: tag_name,
              draft: true,
              generate_release_notes: true
            });

            console.log(release.data);
            return release.data;
      - name: Build gem
        run: bundle exec rake build

      - name: Upload Release Asset
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { repo: { owner, repo } } = context;
            const release = ${{ steps.release.outputs.result }};
            const gemFile = fs.readdirSync('./pkg').find(name => name.endsWith('.gem'));
            const gemPath = `./pkg/${gemFile}`;

            const asset = await github.rest.repos.uploadReleaseAsset({
              owner,
              repo,
              release_id: release.id,
              origin: release.upload_url,
              name: gemFile,
              data: fs.readFileSync(gemPath),
              headers: {
                'content-type': 'application/octet-stream',
                'content-length': fs.statSync(gemPath).size,
              },
            });

            console.log(asset.data);

