name: Ruby

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.2.2"
      - name: Read gem version
        run: |
          version=$(ruby -r rubygems -e "spec = Gem::Specification::load(Dir.glob('*.gemspec').first); puts spec.version")
          echo "gem_version=$version" >> $GITHUB_ENV
        shell: bash
      - name: Create Release
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const { repo: { owner, repo } } = context;
            const version = process.env.gem_version;
            const release = await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: ${{ env.gem_version }},
              draft: true,
              generate_release_notes: true
            });
            return release.data.id;
